name: CI/CD Pipeline

on:
    push:
      branches: [ main, dev, auth ]
    pull_request:
      branches: [ main, dev, auth ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Set Up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.5.1'

        - name: Install Server Dependencies
          run: |
            cd server
            npm install

        - name: Install Client Dependencies
          run: |
            cd client
            npm install

        - name: Compile SCSS
          run: |
            cd client
            npm run compile-scss

        - name: Run ESLint
          run: |
            cd client
            npm run lint

        - name: Build Project...
          run: |
            cd client
            npm run build
      
      